tap "auth0/auth0-cli"
tap "dlvhdr/formulae"
tap "felixkratz/formulae"
tap "frederickbeaulieu/tap", "https://github.com/frederickbeaulieu/homebrew-tap.git"
tap "hashicorp/tap"
tap "nikitabobko/tap"
tap "oven-sh/bun"

brew "bat"
brew "btop"
brew "caddy"
brew "cocoapods"
brew "docker"
brew "doppler"
brew "fd"
brew "ffmpeg"
brew "firebase-cli"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "gnupg"
brew "go"
brew "gopls"
brew "goreleaser"
brew "gradle"
brew "imagemagick"
brew "ios-deploy"
brew "jdtls"
brew "jenv"
brew "jj"
brew "jq"
brew "just"
brew "lefthook"
brew "libimobiledevice"
brew "librsvg"
brew "luarocks"
brew "mas"
brew "maven"
brew "neovim"
brew "nmap"
brew "node"
brew "nvm"
brew "opencode"
brew "openfortivpn"
brew "openjdk"
brew "openjdk@21"
brew "pnpm"
brew "poppler"
brew "python@3.12"
brew "ripgrep"
brew "rsync"
brew "sevenzip"
brew "sonar-scanner"
brew "sql-formatter"
brew "sqlfluff"
brew "starship"
brew "stow"
brew "supabase"
brew "tree-sitter-cli"
brew "watchman"
brew "wget"
brew "xcodegen"
brew "yarn"
brew "yazi"
brew "yq"
brew "zellij"
brew "zoxide"
brew "zsh-autocomplete"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

brew "auth0/auth0-cli/auth0"
brew "dlvhdr/formulae/diffnav"
brew "felixkratz/formulae/sketchybar"
brew "hashicorp/tap/terraform"
brew "oven-sh/bun/bun"

cask "nikitabobko/tap/aerospace"
cask "android-commandlinetools"
cask "android-ndk"
cask "android-studio"
cask "betterdisplay"
cask "bitwarden"
cask "claude-code@latest"
cask "cleanshot"
cask "discord"
cask "docker-desktop"
cask "expo-orbit"
cask "firefox"
cask "flutter"
cask "gcloud-cli"
cask "ghostty"
cask "postman"
cask "slack"
cask "temurin@21"
cask "frederickbeaulieu/tap/tuitui"
cask "unnaturalscrollwheels"

mas "Amphetamine", id: 937984704
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "TestFlight", id: 899247664
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835

vscode "angular.ng-template"
vscode "anthropic.claude-code"
vscode "astro-build.astro-vscode"
vscode "atlassian.atlascode"
vscode "azemoh.one-monokai"
vscode "bradlc.vscode-tailwindcss"
vscode "codeandstuff.package-json-upgrade"
vscode "dbaeumer.vscode-eslint"
vscode "docker.docker"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.auto-close-tag"
vscode "foxundermoon.shell-format"
vscode "irongeek.vscode-env"
vscode "matthewpi.caddyfile-support"
vscode "ms-azuretools.vscode-containers"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.live-server"
vscode "ms-vscode.makefile-tools"
vscode "mtxr.sqltools"
vscode "mtxr.sqltools-driver-mssql"
vscode "mtxr.sqltools-driver-mysql"
vscode "mtxr.sqltools-driver-pg"
vscode "mtxr.sqltools-driver-sqlite"
vscode "pkief.material-icon-theme"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "rust-lang.rust-analyzer"
vscode "saposs.app-studio-remote-access"
vscode "saposs.app-studio-toolkit"
vscode "saposs.sap-hana-driver-for-sqltools"
vscode "sapse.adt-vscode"
vscode "sapse.hana-database-explorer"
vscode "sapse.vsc-extension-sa"
vscode "sapse.vsc-hana-supportability"
vscode "shopify.theme-check-vscode"
vscode "sonarsource.sonarlint-vscode"
vscode "stylelint.vscode-stylelint"
vscode "svelte.svelte-vscode"
vscode "tamasfe.even-better-toml"
vscode "tauri-apps.tauri-vscode"
vscode "thibault-vanderseypen.i18n-json-editor"
vscode "usernamehw.errorlens"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-upgrade"
vscode "vscodevim.vim"

go "github.com/TheZoraiz/ascii-image-converter"
go "github.com/golangci/golangci-lint/v2/cmd/golangci-lint"
go "golang.org/x/tools/cmd/deadcode"

cargo "tauri-cli"

npm "corepack"
